version: "3"
services:
# Service for the Postgres database
  db:
# Pull the latest 'postgres' image
    image: "postgres"
    container_name: "postgres_docker"

# Postgres environment parameters
    environment:
      - POSTGRES_USER=noteapp
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=noteapp_notes

# Bind mount the default Postgres port
    ports:
      - "5432:5432"

# Bind mount local volume for Postgres data
    volumes:
      - ./pg-data:/var/lib/docker/volumes/pgdata

